Improve performance of windows build script on rebuild
ripose-jp/Memento pull request #218
Opened 2024-04-26 06:48 UTC by spacehamster

Amended windows build script to skip redundant work on rebuild

2024-04-26 08:24 UTC, ripose-jp requested changes

2024-04-26 08:24 UTC, ripose-jp commented on README.md
> +    build/release_x86_64\Memento
Change to forward slash

2024-04-26 08:24 UTC, ripose-jp commented on windows/build.sh
> +$PREFIX/bin/cmake -G "Ninja" -DCMAKE_BUILD_TYPE=$build_type ${CMAKE_ARGS} $root
Add quotations around `$root`. It may have spaces in the path.

2024-04-26 08:24 UTC, ripose-jp commented on windows/build.sh
> +cp -r $root/dic Memento
Add `$root` quotations

2024-04-26 08:24 UTC, ripose-jp commented on windows/build.sh
> -mkdir -p Memento_$arch
Please keep the `$arch` stuff

2024-04-26 08:24 UTC, ripose-jp commented on windows/build.sh
> +    python3 $root/windows/mingw-bundledlls.py --copy ./memento.exe
`$root` quotations

2024-04-26 08:25 UTC, ripose-jp commented
[Please update your commit message in accordance with the guidelines.](https://github.com/ripose-jp/Memento/blob/master/CONTRIBUTING.md#commits)

Not that I'm necessarily against this change, but currently it's going to break other scripts. You'll also need to modify `build-installer.sh` as well since it depends on `build.sh`.

I think you might be making this change since you have a suboptimal development environment. If you're using VSCode what I like to do is the following:

* Add Msys2-MINGW64's bin folder to my PATH: `C:\msys64\mingw64\bin`
* [Add Msys2-MINGW64 as a terminal in VSCode](https://stackoverflow.com/questions/45836650/how-do-i-integrate-msys2-shell-into-visual-studio-code-on-window#answer-68253833)
* [Set the default terminal profile to Msys2](https://stackoverflow.com/questions/44435697/change-the-default-terminal-in-visual-studio-code)
* Install the [Microsoft C/C++ Extensions](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack) pack, this will include the CMake plugin
* Install [Native Debug](https://marketplace.visualstudio.com/items?itemName=webfreak.debug) plugin

After doing this, you shouldn't need to run this build script anymore unless you want to make portable binaries. You should be able to just click the **Build** button in VSCode. gdb and everything else should work as well once you set up a `launch.json` using Native Debug.

2024-04-26 11:15 UTC, spacehamster commented
> I think you might be making this change since you have a suboptimal development environment.

Yes, I had been using VSCode without using the CMake Plugin. This solves the main issue I was having. It still rebuilds from when switching build_type (debug/release), but that doesn't happen often to bother me. Do you want me to make the suggested changes or just close the pull request?

Also looking briefly, both Native Debug and Microsoft C/C++ Extensions support debugging with Msys2, is there an advantage to one to the other? I'd just been using Microsoft C/C++ Extensions.

2024-04-27 05:34 UTC, ripose-jp commented
>It still rebuilds from when switching build type (debug/release)

It has to. The binary generated by the compiler when given `-O0` and `-O3` are completely different.

>Do you want me to make the suggested changes or just close the pull request?

I really just use these build scripts to create portable binaries. Adding features useful for development doesn't seem too useful in my opinion, so I lean towards yes.

>Microsoft C/C++ Extensions support debugging with Msys2

That's what they want you to think, but I have never ever gotten visual debug on VSCode to work on Windows except with Native Debug. It's the only reason I recommend it, since I know at this point the problem with Microsoft's extension isn't just user error.

2024-04-27 07:00 UTC, closed without merging