glossarywidget: option to whether display newlines in an list
ripose-jp/Memento pull request #64
Opened 2022-01-13 08:18 UTC by Calvin-Xu

Part of https://github.com/ripose-jp/Memento/issues/62

2022-01-13 20:23 UTC, ripose-jp commented on src/gui/widgets/definition/glossarywidget.cpp
> +            glos += def.replace(QRegExp("\n"), QString("<br>"));
`glos += def.replace('\n', "<br>");`

2022-01-13 20:25 UTC, ripose-jp commented on src/gui/widgets/definition/termwidget.cpp
> +        GlossaryWidget *g = new GlossaryWidget(i + 1, term.definitions[i], list);
80 characters

2022-01-13 20:25 UTC, ripose-jp commented on src/gui/widgets/definition/termwidget.h
> +     * @param list    Whether GlossaryWidget displays newlines in an ordered list
Add period and 80 characters

2022-01-13 20:26 UTC, ripose-jp commented on src/gui/widgets/definition/termwidget.h
> +     * @param list    Whether GlossaryWidget displays newlines in an ordered list
Add period and 80 characters

2022-01-13 20:27 UTC, ripose-jp commented on src/gui/widgets/settings/interfacesettings.cpp
> +    m_ui->checkGlossaryList->setChecked(SETTINGS_INTERFACE_GLOSSARY_LIST_DEFAULT);
80 characters

2022-01-13 22:54 UTC, Calvin-Xu commented
Thanks. I think these changes should have fixed everything. I've just turned the 80 character margin on (I don't usually use Allman braces so turned off most styling related checks; eyeballing it is bad).

I still feel the option belongs more to interface settings, but I've put it in search settings now. Changing it if you change your mind in the future should be easy.

2022-01-14 01:54 UTC, ripose-jp requested changes

2022-01-14 01:54 UTC, ripose-jp commented on src/gui/widgets/definition/definitionwidget.cpp
> +            SETTINGS_SEARCH_LIST_GLOSSARY,
This should be in `initSearch`

2022-01-14 01:54 UTC, ripose-jp commented on src/gui/widgets/settings/searchsettings.ui
> +            <string>Show lines of glossary in an unordered list (restart to take effect)</string>
Don't assume anyone will know what an unordered list is. There is also no reason for this to require a restart to take effect. As long as the correct code is in `initSearch` it shouldn't.

Replace this with
>Use bullet points in term glossaries

2022-01-14 02:06 UTC, Calvin-Xu commented
Changed

2022-01-14 03:47 UTC, merged